# Use rootexample as userpassword credentials
version: "3.1"

services:

  reactnative:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/public
      - ./frontend/src:/src
    ports:
      - 19002:19002
      - 19000:19000
      - 19006:19006

  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
